[package]
name = "ivin/sally"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
ReactRobloxStudioPlugin = "thoughtspinnr/react-roblox-studio-plugin@0.1.4"
Zzlib = "neura-studios/zzlib@0.1.1"
StudioComponents = "sircfenner/studiocomponents@1.0.0"